export const buildReportSummary = ({
  results,
  worstSupport,
  worstUplift,
  selectedCase,
  dT,
  Mt_ULS,
  section,
  extra,
}) => ({
  chartData: results.chartData,
  reactionData: results.reactionData,
  M_Rd: results.M_Rd,
  V_Rd: results.V_Rd,
  F_Rd_Worst: worstSupport.F_Rd * 1000,
  T_Rd_Worst: worstUplift.T_Rd * 1000,
  limitDenom: extra.limitDenom,
  w_limit: extra.w_limit,
  maxMomentNeg: results.maxMomentNeg,
  maxMomentPos: results.maxMomentPos,
  maxMomentAbs: results.maxMomentAbs,
  maxSupportMoment: results.maxSupportMoment,
  maxShear: results.maxShear,
  maxReaction: results.maxReaction,
  maxUplift: results.maxUplift,
  maxDeflection: results.maxDeflection,
  ratios: results.ratios,
  status: results.status,
  advice: results.advice,
  governingCases: results.governingCases,
  stress_span: results.stress_span,
  stress_support: results.stress_support,
  sigma_limit: results.sigma_limit,
  supportLocs: results.supportLocs,
  extrema: results.extrema,
  creepMode: results.creepMode,
  phiShear: results.phiShear,
  phiBending: results.phiBending,
  panelWidth: results.panelWidth,
  screwCount: results.screwCount,
  qDead_kPa: results.qDead_kPa,
  qLive_kPa: results.qLive_kPa,
  qWind_kPa: results.qWind_kPa,
  qSLS_kPa: selectedCase.qSLS_kPa,
  qULS_kPa: selectedCase.qULS_kPa,
  dT_deg: dT,
  Mt_ULS_kNm: Mt_ULS / 1e6,
  EI: section.EI,
  GA_inst: section.GA_inst,
  GA_long: extra.GA_long,
  EI_long: extra.EI_long,
  e: section.e,
  Af1: section.Af1,
  Af2: section.Af2,
  Ac: section.Ac,
  I_eq: section.I_eq,
  zMax: section.zMax,
  sigma_w: section.sigma_w,
  sigma_w_approx: section.sigma_w_approx,
  sigma_w_declared: section.sigma_w_declared,
  sigma_w_design: section.sigma_w_design,
  sigma_w_source: section.sigma_w_source,
  wrinklingDeclaredMissing: section.wrinklingDeclaredMissing,
  wrinklingFallbackMode: section.wrinklingFallbackMode,
  sigma_y_design: section.sigma_y_design,
  gammaG: extra.gammaG,
  gammaQ: extra.gammaQ,
  gammaThermal: extra.gammaThermal,
  dC: section.dC,
  tF1: section.tF1,
  tF2: section.tF2,
  compressiveModulus: section.compressiveModulus,
  wrinklingMode: section.wrinklingMode,
  redistributionMode: extra.redistributionMode,
  redistributionEnabled: extra.redistributionEnabled,
});
